# Generated by Django 4.2.7 on 2024-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='arrival_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='departure_date',
            field=models.CharField(max_length=10),
        ),
    ]
