# Generated by Django 4.2.7 on 2024-04-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_alter_flightprice_price'),
        ('user', '0003_alter_reservation_flight_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='flight_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='arrival_reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_reservation', to='flight.flightschedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='departure_reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departure_reservation', to='flight.flightschedule'),
        ),
    ]
